all:
	make run

#Starts the environment holding Django (might need to directly type)
startenv:
	source env/bin/activate	

#Runs the Django server with default port as 8000
run:
	python manage.py runserver
